#!/bin/bash
[[ $EUID -ne 0 ]] && echo "error: you cannot perform this operation unless you are root." && exit 1
# Upgrade system and AUR packages
sudo -u $SUDO_USER bash -c "pacaur -Syu"
# Remove orphaned packages
echo :: Starting Package cleanup...
if [[ $(pacman -Qtdq | head -c1 | wc -c) -eq 0 ]]; then
    echo " there is nothing to do"
else
    pacman -Rns $(pacman -Qtdq)
fi
# Clean package cache (because I made root partition too small and I'm dumb)
paccache -r --quiet
paccache -rk 1 --quiet
paccache -ruk0 --quiet
